### ISSUE TITLE
Disable Assignment List extension on Windows

### ISSUE THREAD

**Issue by lgpage** [conda-forge/nbgrader-feedstock#12]
@jhamrick I wonder if we should not just disable the Assignment List extension on Windows on installation to eliminate this error:

```bash
[NotebookApp | CRITICAL] Sorry, the exchange is not available on Windows.
[NotebookApp | ERROR] Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\server_extensions\assignment_list\handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\exchange\list.py", line 129, in start
        super(ExchangeList, self).start()
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\exchange\exchange.py", line 120, in start
        self.fail("Sorry, the exchange is not available on Windows.")
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\exchange\exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Sorry, the exchange is not available on Windows.
```

**Comment by jhamrick** [comment]
Did you mean to open this on the nbgrader repo?

But yes, this seems like a reasonable thing to do. I think it would require checking for windows in `nbgrader/__init__.py` and then dynamically adding the assignment list to `_jupyter_nbextension_paths` and `_jupyter_server_extension_paths` if it's not windows.

**Comment by jhamrick** [comment]
Closing this since it's fixed in the main nbgrader repo now.
